FROM eclipse-temurin:17-jdk-jammy AS build

WORKDIR /app

COPY src ./src
COPY .mvn .mvn
COPY mvnw pom.xml ./

RUN ./mvnw -B package -DskipTests


FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]